### ISSUE TITLE
Update laravel to laravel 9 and security updates

### ISSUE THREAD

**Issue by PatricNox** [fossbarrow/laravel-clean-docker#4]
This repo is old and needs to be maintained.

* security updates
* update to laravel 9.x

**Comment by elvinlari** [comment]
Hello PatricNox, I can help with this

**Comment by elvinlari** [comment]
Assign me this issue under Hacktoberfest

**Comment by PatricNox** [comment]
> Assign me this issue under Hacktoberfest

Hi, no need to be assigned. I don't want to lock it to one person incase it never gets finished, so whoever makes the first fix  eliminates this issue.

**Comment by elvinlari** [comment]
I agree. Thank you

**Comment by elvinlari** [comment]
@PatricNox I have updated Laravel to version 9, PHP to 8.1 and the composer packages. 

However, am getting a permission denied error when I try to push to your repository.

**Comment by PatricNox** [comment]
> @PatricNox I have updated Laravel to version 9, PHP to 8.1 and the composer packages.
> 
> However, am getting a permission denied error when I try to push to your repository.

You need to fork the repo and make a PR from your fork
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by elvinlari** [comment]
Thank you. I have created a pull request.

**Comment by PatricNox** [comment]
PR created, thanks!
